### PR TITLE
Resend subscription on load

### PR DESCRIPTION
**Pull request by wibblymat**
Matt pointed out that the subscription details can change in between page loads, so let's send the subscription details again when we initialise.

R: @ithinkihaveacat @gauntface @owencm

### CODE REVIEW

**Comment by wibblymat** [comment]
@gauntface in some other PR you asked about the `userId`. I can't find that thread now, so I'll answer here.

`userId` is just *some value* that the page is using to uniquely identify the current user. It could be anything. The important thing is that you need to send something like that to the server so that the server knows which clients to push to for which users.

**Comment by wibblymat** [comment]
@ithinkihaveacat @gauntface @owencm this old PR is now ready for review :)

**Comment by gauntface** [comment]
The PR itself is good assuming the developer wants to pass over the endpoint to the library.

If the developer was using a third party service like firebase and the intended use of the subscription object was to store in firebase via the firebase library, making us of ACL's etc, this wouldn't be possible with this current architecture (or at least not obvious).

**Comment by wibblymat** [comment]
We'll handle that case separately then.

**Pull request merged**
