### PR TITLE
Add public requestPermission method

### PR DESCRIPTION
**Pull request by wibblymat**
@owencm @gauntface 

Matt and I discussed this face to face this morning and decided this would be better as a PR so that we could talk through what we want to do here.

I'll be honest, though... now that I've gone through the chore of rolling back master and creating the PR I can't remember what the objections might have been. Matt?

### CODE REVIEW

**Comment by wibblymat** [comment]
P.S., I also enabled branch protection for master :smile:

**Comment by gauntface** [comment]
Few things I was curious about:

1.) What is the benefit of this method being on the client object? Any chance of rough sample code?
2.) I was planning on adding Permission API support after the event dispatch PR got in, that would give us events for the lifecycle of the web app. But feels like you have a use case that doesn't fit into this

**Comment by owencm** [comment]
Thanks for saving me from my screw up Mat!

@gauntface 1. You mean as opposed to requiring developers to call Notification.requestPermission()?

My use case is that calling subscribe() is a very poor way of asking for permission, since the promise only resolves after a RTT to the server once the user presses accept. For this reason there is frequently a long delay between the user accepting the permission and the site knowing - aka being able to update it's UI.

My suggestion when writing code for push is to do something like:

```
// Run the following if the user clicks to enable push somewhere in the UI
dimScreen();
pushClient.requestPermission().then((decision) => {
  // TODO: Handle failure of requesting permission
  undimScreen();
  pushClient.subscribe();
})
```

Instead of dimming the screen you can imagine this showing explanatory text or whatever.

Does that use case and sample code make sense?

**Comment by gauntface** [comment]
@wibblymat Looks like the event firing code is gone from master branch now after the changes.

**Comment by wibblymat** [comment]
@gauntface fuuuuuuu...  I'll see what I can do.

**Comment by owencm** [comment]
@gauntface looks like you've got some ACLing issues going on :)

I'll drop you both an email about what I personally view the purpose of this library as by the way if that helps.

**Comment by gauntface** [comment]
This method is now public on the master branch so going to close this PR.

I've also added an event based approach in case people prefer that.

**Pull request closed without merging**
