### PR TITLE
Adding notificationHandler method to the service worker API.

### PR DESCRIPTION
**Pull request by wibblymat**
Usage:

```
// Most basic option, no fallback or custom behaviour
self.addEventListener('push', goog.propel.worker.notificationHandler);

// OR, if you want more control
self.addEventListener('push', function(event) {
  if (!goog.propel.worker.notificationHandler(event)) {
    // the function returns false if for some reason no notification is shown
    displayFallbackNotification();
  }

  // Do some other stuff...
});

### CODE REVIEW

**Comment by wibblymat** [comment]
R: @owencm @ithinkihaveacat @gauntface

**Comment by ithinkihaveacat** [comment]
Probably I'm missing something but I wasn't expecting the `push` handler to be a stateless function--I imagined the handler would be a method attached to the pushClient itself, and have access to the pushClient's settings and configuration. How does this model handle browsers that don't support message bodies, in which the bodies need to be retrieved from some endpoint known to the pushClient? Or if the pushClient has a `VERBOSE` flag or similar that enables logging?

**Comment by gauntface** [comment]
The first option just shows up the Chrome notification right?

Other than that this is ok.

**Comment by wibblymat** [comment]
@ithinkihaveacat This function is the first thing in the *worker* API. PushClient isn't available here.

For symmetry I did consider making a PushWorker class, and having this be a method on that, but there isn't any state to capture. This is a dead basic implementation that works only if payloads are used.

For the more practical, actually-usable-right-now, case we can add some other helpers. But I think that simple, composable functions is a better API than having a single handler that does everything.

@gauntface In the first option all of the details for the notification must be in the payload, otherwise nothing happens and Chrome will show the default notification.

**Pull request merged**
