### PR TITLE
Event dispatcher

### PR DESCRIPTION
**Pull request by wibblymat**
@gauntface Rescued it!

### CODE REVIEW

**Comment by wibblymat** [comment]
@gauntface I needed to create a PR because of branch protection, just need to work out how to placate @googlebot  so we can merge.

**Comment by gauntface** [comment]
I think me responding to this PR will make the CLA bot happy.

**Comment by gauntface** [comment]
I wrote this.

**Comment by gauntface** [comment]
@googlebot this is ok

**Pull request closed without merging**
